# Stage 1
# Immagine docker per buildare
FROM node:21.2.0 AS build-stage

WORKDIR /app-web

# Copia i file del progetto nell'immagine docker
COPY src/main/web/ .

# installazione delle dipendenze
RUN npm install

# build del progetto
RUN npm run build

# Stage 2
# Immagine docker NGINX per servire l'app compilata
FROM nginx:latest

WORKDIR /usr/share/nginx/html

# Copia i file compilati dall'immagine di build precedente
COPY --from=build-stage /app-web/dist/browser /usr/share/nginx/html

# Copia il file di configurazione personalizzato di NGINX
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Espone la porta 80 per il traffico HTTP
EXPOSE 80

# Avvia NGINX in modalità daemon quando il container viene avviato
CMD ["nginx", "-g", "daemon off;"]
